export const users = [
  {
    _id: '648f36758f8e136e6706e6cf',
    index: 0,
    guid: '0ec26f1f-091e-42ec-8f94-0d149bb5370c',
    isActive: true,
    balance: '$3,000.62',
    picture: 'http://placehold.it/32x32',
    age: 28,
    eyeColor: 'green',
    name: 'Hurst Fisher',
    gender: 'male',
    company: 'BIOTICA',
    email: 'hurstfisher@biotica.com',
    phone: '+1 (901) 470-3255',
    address: '683 Pooles Lane, Troy, Wyoming, 5476',
    about:
      'Incididunt et id enim elit duis dolore et esse commodo est est pariatur quis. Reprehenderit voluptate mollit reprehenderit voluptate in. Quis enim nulla aliquip enim amet culpa eiusmod irure laborum exercitation. Enim id non elit elit est adipisicing dolore proident cillum ipsum minim in. Minim ipsum aute cillum in officia aute minim veniam mollit consequat voluptate incididunt elit. In mollit eu anim incididunt ex eiusmod non in anim dolore culpa enim. Et reprehenderit irure labore ullamco pariatur.\r\n',
    registered: '2015-03-10T05:32:35 -04:00',
    latitude: 33.298129,
    longitude: -164.972098,
    tags: [
      'nisi',
      'veniam',
      'reprehenderit',
      'ea',
      'dolore',
      'ipsum',
      'cillum',
    ],
    friends: [
      {
        id: 0,
        name: 'Polly Steele',
      },
      {
        id: 1,
        name: 'Vonda Riddle',
      },
      {
        id: 2,
        name: 'Alyson Chase',
      },
    ],
    greeting: 'Hello, Hurst Fisher! You have 2 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '648f3675ddd8e21700bf41fc',
    index: 1,
    guid: 'b79e7398-c39f-4a5a-b1de-272d1ec459b5',
    isActive: true,
    balance: '$1,753.46',
    picture: 'http://placehold.it/32x32',
    age: 31,
    eyeColor: 'green',
    name: 'Millicent Parrish',
    gender: 'female',
    company: 'EARWAX',
    email: 'millicentparrish@earwax.com',
    phone: '+1 (863) 420-3693',
    address: '202 George Street, Leroy, Georgia, 2843',
    about:
      'Do quis consectetur id sint tempor excepteur non eiusmod veniam proident velit ex mollit. Sint dolore occaecat fugiat incididunt voluptate adipisicing est laboris officia. Excepteur incididunt quis quis mollit. Esse quis nisi enim minim est nostrud. Amet ex quis nulla sunt occaecat dolor fugiat adipisicing. Exercitation velit duis est nulla esse irure aute Lorem non irure ea pariatur elit. Sit sint enim duis occaecat dolor aute sit sit qui.\r\n',
    registered: '2019-02-21T01:58:52 -04:00',
    latitude: 43.818083,
    longitude: 48.284772,
    tags: ['ea', 'nulla', 'irure', 'cillum', 'elit', 'qui', 'laborum'],
    friends: [
      {
        id: 0,
        name: 'Yesenia Ellis',
      },
      {
        id: 1,
        name: 'Kara Chavez',
      },
      {
        id: 2,
        name: 'Rivera Terry',
      },
    ],
    greeting: 'Hello, Millicent Parrish! You have 1 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '648f3675bf9c44543210ed68',
    index: 2,
    guid: '5d4f8ecd-6560-4c1d-9108-a1095e5a3ed6',
    isActive: true,
    balance: '$3,507.00',
    picture: 'http://placehold.it/32x32',
    age: 27,
    eyeColor: 'blue',
    name: 'Wynn Snyder',
    gender: 'male',
    company: 'EXPOSA',
    email: 'wynnsnyder@exposa.com',
    phone: '+1 (971) 557-3564',
    address: '418 Duffield Street, Vivian, Ohio, 9154',
    about:
      'Consequat proident ad ad ex irure laborum sit minim ut quis qui laborum Lorem sunt. Excepteur est dolore officia magna eu occaecat aute dolore excepteur. Labore cillum dolor deserunt incididunt nisi labore do incididunt proident est officia duis proident excepteur. Esse ad non ullamco laborum. Dolore magna velit ex minim minim laboris aliquip enim labore non. Consequat ut labore incididunt ullamco duis reprehenderit magna.\r\n',
    registered: '2023-04-14T01:53:43 -04:00',
    latitude: -57.809685,
    longitude: 154.890328,
    tags: ['ut', 'labore', 'nisi', 'et', 'laboris', 'commodo', 'cillum'],
    friends: [
      {
        id: 0,
        name: 'Merrill Bentley',
      },
      {
        id: 1,
        name: 'Angelica Barry',
      },
      {
        id: 2,
        name: 'Camacho Berg',
      },
    ],
    greeting: 'Hello, Wynn Snyder! You have 6 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '648f36754f1aa6439feec1fb',
    index: 3,
    guid: '8a938643-4004-4559-9503-865f4bd3ccf6',
    isActive: true,
    balance: '$1,152.40',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'blue',
    name: 'Amy Buchanan',
    gender: 'female',
    company: 'COMSTAR',
    email: 'amybuchanan@comstar.com',
    phone: '+1 (968) 420-3517',
    address: '873 Kosciusko Street, Bergoo, Alabama, 167',
    about:
      'Nostrud aute officia excepteur esse. Fugiat consectetur proident cupidatat fugiat reprehenderit id magna elit mollit dolor pariatur magna velit. Dolore aute ullamco commodo quis consequat sint non aute occaecat Lorem. Excepteur voluptate sint labore sunt dolor. Excepteur esse officia culpa pariatur. Eiusmod ipsum laborum fugiat sint voluptate aliqua.\r\n',
    registered: '2021-01-11T02:31:57 -04:00',
    latitude: -63.393956,
    longitude: 39.13506,
    tags: ['qui', 'culpa', 'irure', 'magna', 'duis', 'laboris', 'ullamco'],
    friends: [
      {
        id: 0,
        name: 'Washington Hill',
      },
      {
        id: 1,
        name: 'Madden Middleton',
      },
      {
        id: 2,
        name: 'Giles Holden',
      },
    ],
    greeting: 'Hello, Amy Buchanan! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '648f3675ce8e3359bf15a777',
    index: 4,
    guid: '0610d15f-d291-4c69-8658-83df8e566d78',
    isActive: true,
    balance: '$1,995.60',
    picture: 'http://placehold.it/32x32',
    age: 23,
    eyeColor: 'brown',
    name: 'Kerri Hatfield',
    gender: 'female',
    company: 'DANCITY',
    email: 'kerrihatfield@dancity.com',
    phone: '+1 (850) 560-3551',
    address: '585 Herzl Street, Dellview, Palau, 553',
    about:
      'Magna sit esse sunt laboris aliquip in qui culpa ad dolore commodo adipisicing mollit. Qui qui cillum incididunt deserunt. Qui pariatur consectetur amet voluptate veniam reprehenderit eu. Id nisi nulla veniam pariatur commodo mollit veniam quis ad ipsum consectetur magna tempor.\r\n',
    registered: '2019-05-03T08:19:04 -04:00',
    latitude: -45.758545,
    longitude: 77.200588,
    tags: [
      'ut',
      'do',
      'nulla',
      'exercitation',
      'reprehenderit',
      'sint',
      'eiusmod',
    ],
    friends: [
      {
        id: 0,
        name: 'Sharpe Green',
      },
      {
        id: 1,
        name: 'Santiago Olson',
      },
      {
        id: 2,
        name: 'Jeannie Sullivan',
      },
    ],
    greeting: 'Hello, Kerri Hatfield! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
];
